AllCops:
  Exclude:
    - 'bin/bundle'

Metrics/LineLength:
  Max: 125

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 12

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
